[package]
name = "rust-webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#for GET
reqwest = "0.11"
httparse = "1.8.0"
dotenv = "0.15.0"
